name: password_generator
description: "A secure password generator app"
publish_to: 'none'

version: 1.0.0+7

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  local_auth: ^2.1.6
  provider: ^6.1.1
  lucide_icons: ^0.257.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icon.png
    - assets/words/3l.json
    - assets/words/4l.json
    - assets/words/5l.json
    - assets/words/6l.json
    - assets/words/7l.json

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

dependency_overrides:
  intl: ^0.19.0